function Hd = generate_fir_filt
%GENERATE_FIR_FILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 29-Jun-2024 10:06:30

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

Fpass = 5;                % Passband Frequency
Fstop = 10;                % Stopband Frequency
Dpass = 0.00028782312868;  % Passband Ripple
Dstop = 0.31622776602;     % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
